# Generated by Django 3.0.5 on 2024-01-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
