# Generated by Django 3.0.5 on 2024-01-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20240124_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.CharField(default=None, max_length=90, null=True, unique=True),
        ),
    ]
