# Generated by Django 3.0.5 on 2024-01-24 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0011_parent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='parent_user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_user',
        ),
        migrations.CreateModel(
            name='Teacher_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
