# Generated by Django 3.0.5 on 2024-01-28 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20240124_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='Curriculum/')),
                ('medium_name', models.CharField(choices=[('English', 'English'), ('Gujarati', 'Gujarati')], default='English', max_length=30)),
                ('cls_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.Class')),
            ],
        ),
    ]
