# Generated by Django 3.0.5 on 2024-01-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_stubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default=None, max_length=70, null=True)),
                ('desc', models.TextField()),
                ('ptm_date', models.DateField()),
                ('ptm_time', models.TimeField()),
                ('medium_name', models.CharField(choices=[('English', 'English'), ('Gujarati', 'Gujarati')], default='English', max_length=30)),
                ('cls_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.Class')),
            ],
        ),
    ]
