# Generated by Django 3.0.5 on 2024-01-28 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_ptm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stubject',
            new_name='Subject',
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=25)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('medium_name', models.CharField(choices=[('English', 'English'), ('Gujarati', 'Gujarati')], default='English', max_length=30)),
                ('cls_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.Class')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher')),
            ],
        ),
    ]
