# Generated by Django 3.0.5 on 2024-01-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20240128_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='cls_name',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='medium_name',
        ),
    ]
