# Generated by Django 3.0.5 on 2024-01-29 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20240128_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='fname',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='lname',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='p_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Parent_user'),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_img',
            field=models.ImageField(default=None, null=True, upload_to='parent_img/'),
        ),
    ]
