# Generated by Django 3.0.5 on 2024-02-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_student_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('exam_date', models.DateField()),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('exam', models.CharField(choices=[('Semester-1', 'Semester-1'), ('Semester-2', 'Semester-2')], max_length=20, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Subject')),
            ],
        ),
    ]
