# Generated by Django 3.0.5 on 2024-02-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='fname',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lname',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Teacher_user'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_img',
            field=models.ImageField(default=None, null=True, upload_to='teacher_img/'),
        ),
    ]
