# Generated by Django 3.0.5 on 2024-02-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20240208_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='acd_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fee',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_no',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
