# Generated by Django 3.0.5 on 2024-02-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20240217_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll_no']},
        ),
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='year',
            field=models.PositiveIntegerField(default=2024, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='doj',
            field=models.DateField(null=True),
        ),
    ]
