# Generated by Django 3.0.5 on 2024-03-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20240218_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
