# Generated by Django 3.0.5 on 2024-03-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='expr',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pg_degree_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pg_overall_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pg_uni_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='ug_degree_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='ug_overall_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='ug_uni_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
