# Generated by Django 5.0.1 on 2024-03-23 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_remove_gallery_img_name_alter_activity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('B+', 'B+'), ('C', 'C'), ('F', 'F')], default='B', max_length=3),
        ),
        migrations.AddField(
            model_name='marks',
            name='total_marks_obtained',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Teacher_has_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium_name', models.CharField(choices=[('English', 'English'), ('Gujarati', 'Gujarati')], default='English', max_length=30)),
                ('cls_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='school.class')),
                ('cls_teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='school.teacher')),
            ],
        ),
    ]
