# Generated by Django 5.0.3 on 2024-04-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_marks_grade_marks_total_marks_obtained_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='day',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='teacher',
        ),
        migrations.AddField(
            model_name='timetable',
            name='cls_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='medium_name',
            field=models.CharField(choices=[('English', 'English'), ('Gujarati', 'Gujarati')], default='English', max_length=30),
        ),
        migrations.AddField(
            model_name='timetable',
            name='pdf',
            field=models.FileField(default=None, upload_to='TimeTable/'),
        ),
    ]
